(load-file "~/.emacs.d/init-common.el")
(load-file "~/.emacs.d/init-mail.el")
(load-file "~/.emacs.d/init-bbdb.el")
(load-file "~/.emacs.d/init-surround.el")
(load-file "~/.gnus.el")
(call-interactively 'gnus)
